name: Rust AOC
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: check
        run: cargo check
      - name: Code style
        run: cargo clippy
      - name: Test
        run: cargo test
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Release build
        run: cargo build --bins --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries-${{ matrix.os }}
          if-no-files-found: error
          path: |
            target/release/day*
