name: Rust AOC
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Build
        run: cargo build --release
      - name: Code style
        run: cargo clippy
      - name: Test
        run: cargo test
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          if-no-files-found: error
          path: |
            target/release/day*
            day*/input.txt
  solve:
    runs-on: ubuntu-latest
    depends-on: check
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: binaries
      - name: Debug
        run: ls -R
